# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: KhaledsApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

      deploy:
runs-on: self-hosted
needs: build
steps:
- name: Download the artifacts from Github (from the build job)
uses: actions/download-artifact@v4
with:
name: app-artifacts
- name: Stop the application service
run: |
sudo systemctl stop GithubActionsDemo.service
- name: Deploy the the application
run: |
sudo rm -Rf /opt/GithubActionsDemo || true
sudo cp -r /home/azureuser/actions-runner/_work/GithubActionsDemo/GithubActionsDemo/
/opt/GithubActionsDemo
- name: Start the application service
run: |
sudo systemctl start GithubActionsDemo.service
